CREATE TABLE USERS (
  "USERID" 		VARCHAR2(32 CHAR) NOT NULL, 
  "USERNAME" 	VARCHAR2(256 CHAR) NOT NULL, 
  "PASSWORD" 	VARCHAR2(256 CHAR) NOT NULL, 
  "NICKNAME" 	VARCHAR2(256 CHAR) NOT NULL,
  "EMAIL"		VARCHAR2(256 CHAR) NOT NULL,
  CONSTRAINT "USERS_PK" PRIMARY KEY(USERID) ENABLE
)
/
COMMENT ON TABLE 	"USERS" 			IS   'Users Table'
/
COMMENT ON COLUMN 	"USERS"."USERID" 	IS   'User ID'
/
COMMENT ON COLUMN 	"USERS"."USERNAME" 	IS   'User Name'
/
COMMENT ON COLUMN 	"USERS"."PASSWORD" 	IS   'User Password'
/
COMMENT ON COLUMN 	"USERS"."NICKNAME" 	IS   'User NickName'
/
COMMENT ON COLUMN 	"USERS"."EMAIL" 	IS   'User Email'
/
