DROP TABLE WLOGDATA
/
DROP TABLE WLOGEV
/
DROP TABLE WLOGTY
/
DROP SEQUENCE WLOGEVID_SQ
/
DROP SEQUENCE SEQ_PROPERTY
/
DROP SEQUENCE SQ_WUSERS
/
DROP SEQUENCE WAUDITID_SQ
/
DROP PACKAGE PL_WAUTH
/
DROP TABLE WMAIL2APPL CASCADE CONSTRAINTS
/
DROP TABLE WMAIL CASCADE CONSTRAINTS
/
DROP TABLE WREG2SYN CASCADE CONSTRAINTS
/
DROP TABLE WPROPERTY CASCADE CONSTRAINTS
/
DROP TABLE WPWDSYNTAX CASCADE CONSTRAINTS
/
DROP TABLE WPROF2ACT CASCADE CONSTRAINTS
/
DROP TABLE WUSR2APPL2AREA2PROF CASCADE CONSTRAINTS
/
DROP TABLE WUSR2APPL2AREA CASCADE CONSTRAINTS
/
DROP TABLE WUSR2APPL CASCADE CONSTRAINTS
/
DROP TABLE WAREA CASCADE CONSTRAINTS
/
DROP TABLE WPROF CASCADE CONSTRAINTS
/
DROP TABLE WUSERS CASCADE CONSTRAINTS
/
DROP TABLE WAPPL CASCADE CONSTRAINTS
/
DROP TABLE WPAR2APPL CASCADE CONSTRAINTS
/
DROP TABLE WWWPARLOGIN CASCADE CONSTRAINTS
/
DROP TABLE WMREQ CASCADE CONSTRAINTS
/
DROP TABLE WREGROUP CASCADE CONSTRAINTS
/
DROP TABLE WCUST CASCADE CONSTRAINTS
/
DROP TABLE WAUDIT CASCADE CONSTRAINTS
/
