INSERT INTO USERS (USERID,USERNAME,PASSWORD,NICKNAME,EMAIL) VALUES (1,'user1','password1','UserNickname1','user1@test.com')
INSERT INTO USERS (USERID,USERNAME,PASSWORD,NICKNAME,EMAIL) VALUES (2,'user2','password2','UserNickname2','user2@test.com')
INSERT INTO USERS (USERID,USERNAME,PASSWORD,NICKNAME,EMAIL) VALUES (3,'user3','password3','UserNickname3','user3@test.com')
INSERT INTO USERS (USERID,USERNAME,PASSWORD,NICKNAME,EMAIL) VALUES (4,'user4','password4','UserNickname4','user4@test.com')
INSERT INTO USERS (USERID,USERNAME,PASSWORD,NICKNAME,EMAIL) VALUES (5,'user5','password5','UserNickname5','user5@test.com')
INSERT INTO USERS (USERID,USERNAME,PASSWORD,NICKNAME,EMAIL) VALUES (6,'user6','password6','UserNickname6','user6@test.com')
INSERT INTO USERS (USERID,USERNAME,PASSWORD,NICKNAME,EMAIL) VALUES (7,'user7','password7','UserNickname7','user7@test.com')
COMMIT